version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./certs:/etc/nginx/certs
      # - ./html:/usr/share/nginx/html
    networks:
      - nginx_proxy
    # depends_on:
    #   - app

  app1:
    image: nginx:alpine
    container_name: app1
    restart: always
    volumes:
      - ./apps/app1:/usr/share/nginx/html
    networks:
      - nginx_proxy

  app2:
    image: nginx:alpine
    container_name: app2
    restart: always
    # ports:
    #   - 8181:80
    volumes:
      - ./apps/app2:/usr/share/nginx/html
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
